baseURL: 'http://localhost:8080/'
title: NullTrace Blog
author: ["codacker"]
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: nulltrace
enableRobotsTXT: true
params:
  base_color: bg-gray-800
  paginator_pages: '5'
  archive_dropdown: 'false'
  tagsLimit: 20
  darkmode: light
  post:
    thumbnail: true
    noimage: true
    thumbnail_height: h-44
    thumbnail_width: w-auto
    description: '130'
  widgets:
    display: true
    widgets:
      - search
      - archive
      - category
      - tags
      - recent
menu:
  main:
    - identifier: home
      name: Home
      url: https://nulltrace.in/
      weight: 1
    - identifier: about
      name: About
      url: https://nulltrace.in/about
      weight: 2
    - identifier: contact
      name: Contact
      url: https://nulltrace.in/contact
      weight: 3
taxonomies:
  category: categories
  tag: tags
  archive: archives
privacy:
  vimeo:
    disabled: false
    simple: true
  twitter:
    disabled: false
    enableDNT: true
    simple: true
  instagram:
    disabled: false
    simple: true
  youtube:
    disabled: false
    privacyEnhanced: true
services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
build:
  writeStats: true
